### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by mprokopiev** [tropicoo/hikvision-camera-bot#49]
Hi team,

Couple items I noticed while deploying and using this:
1) is it needed to build a new image for srs considering the [public image](https://ossrs.io/lts/en-us/docs/v4/doc/getting-started) is already available and has lesser size? I used ossrs/srs:4 with this bot and it worked fine (ossrs/srs:5 didn't work). If compatibility is a concern - exact compatible version can be used as image tag to avoid upgrading to non compatible release;

2) it would make sense to create bind volume to map configuation files, i.e.:
```
  hikvision-srs-server:
    volumes:
      - /hikvision-camera-bot/srs/conf/:/usr/local/srs/conf/

  hikvision-camera-bot:
    volumes:
      - /media/hdd/other/hik-dvr/:/data/dvr
      - /hikvision-camera-bot/hikvision-camera-bot/configs/:/app/configs
```
_/hikvision-camera-bot/srs/conf/_ and _/hikvision-camera-bot/hikvision-camera-bot/configs/_ would host docker.conf for SRS and configuration files for bot accordingly. 

If not, image rebuild is required on each change in configuration file;

3) looks like all streams (youtube, dvr, telegram, srs were tested) are hardcoded to hikvision_srs_server container name (or service name if docker-compose is used);

4) for Telegram stream, I had to change acodec codec to aac in encoding-templates.json to make it working:
```
    "kitchen_telegram": {
      "null_audio": false,
      "loglevel": "error",
      "vcodec": "copy",
      "acodec": "aac",
      "asample_rate": -1,
      "format": "flv",
      "rtsp_transport_type": "tcp"
    }
```

Maybe that's an issue with my camera model (DS-2CV2Q21FD-IW) only. 

Thanks,
Maksym
